### ISSUE TITLE
`aspect ratio` isn't always aligned

### ISSUE THREAD

**Issue by arindal1** [simanders/ext-video-player#4]
The aspect ratio of the video playing in Fullscreen isn't aligned to the middle. As a result there is a huge `black bar` only at the bottom of the video.
**Note:** This only happens when video is in Fullscreen.

@simanders let's work on this issue.

**Comment by simanders** [comment]
@arindal1 Yes, I noticed that when I was working on it. I tried a lot of things, but nothing worked. You try something, let's see if that works.
